"use client";

import "./globals.css";

import { PropsWithChildren } from "react";
import { RecoilRoot } from "recoil";
import ThemeProvider from "../providers/ThemeProvider";

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <head>
        <title>Next App Starter</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>

      <body>
        <RecoilRoot>
          <ThemeProvider>{children}</ThemeProvider>
        </RecoilRoot>
      </body>
    </html>
  );
}
