import { PropsWithChildren } from 'react'
import RootProvider from '@providers/RootProvider'
import ThemeRegistry from '@providers/ThemeRegistry'
import { getTranslations } from 'i18n'
import { NextIntlClientProvider } from 'next-intl'

import './globals.css'

export default async function RootLayout({ children }: PropsWithChildren) {
  const { messages, locale, theme } = await getTranslations()

  return (
    <html lang={locale}>
      <head>
        <title>Next App Starter</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>

      <body>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <RootProvider savedTheme={theme}>
            <ThemeRegistry>{children}</ThemeRegistry>
          </RootProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
